project:
  type: website
  output-dir: docs
website:
  title: "rapport"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: "Télécharger PDF"
        href: rapport.pdf # Assurez-vous que le fichier rapport.pdf est dans le répertoire docs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
