name: Deploy Quarto Project

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Render and Publish
        env:
          GITHUB_PAT: ${{ secrets.GH_PAT }}
        run: |
          quarto publish gh-pages
